---

- name: 'Stat {{ beat_name }} output file (win)'
  win_stat:
    path: '{{ beat_output_file }}'
  register: output_stat

- name: '{{ beat_name }} output file stats'
  debug:
    var: output_stat

- name: "Assert that {{ beat_name }} output file exists"
  assert:
    that:
      - "output_stat.stat.exists"
      - "output_stat.stat.size > 0"

- name: 'Stat {{ beat_name }} log file (win)'
  win_stat:
    path: '{{ beat_log_file }}'
  register: log_stat

- name: '{{ beat_name }} log file stats'
  debug:
    var: log_stat

- name: 'Assert that {{ beat_name }} log file exists'
  assert:
    that:
      - "log_stat.stat.exists"
      - "log_stat.stat.size > 0"

- name: 'Stat {{ beat_name }} registry file (win)'
  win_stat:
    path: '{{ beat_registry_file }}'
  register: registry_stat
  when: registry_file != ''

- name: '{{ beat_name }} registry file stats'
  debug:
    var: registry_stat
  when: registry_file != ''

- name: 'Check {{ beat_name }} registry file'
  assert:
    that:
      - "registry_stat.stat.exists"
      - "registry_stat.stat.size > 0"
  when: registry_file != ''

- name: 'Get {{ beat_name }} metrics (win)'
  win_shell: 'cat -Encoding UTF8 {{ beat_metrics_file }} | select -First 1'
  register: log_metrics_win

- set_fact: log_metrics_event='{{ log_metrics_win.stdout | from_json }}'

- name: '{{ beat_name }} monitoring metrics (win)'
  debug:
    var: log_metrics_event

- name: 'Check {{ beat_name }} has monitoring metrics (win)'
  assert:
    that:
      - "log_metrics_event.beat.cpu.system.ticks >= 0"
      - "log_metrics_event.beat.cpu.system.time.ms >= 0"
      - "log_metrics_event.beat.cpu.total.ticks >= 0"
      - "log_metrics_event.beat.cpu.total.time.ms >= 0"
      - "log_metrics_event.beat.cpu.user.ticks >= 0"
      - "log_metrics_event.beat.cpu.user.time.ms >= 0"
      - "log_metrics_event.beat.info.ephemeral_id"
      - "log_metrics_event.beat.info.uptime.ms"
      - "log_metrics_event.system.cpu.cores"
      - "'load' not in 'log_metrics_event.system.cpu'"
  # These metric names were established in 6.3.
  when: "version | version_compare('6.3', '>=')"

- name: 'Check {{ beat_name }} reports the number of open handles (win)'
  assert:
    that:
      - "log_metrics_event.beat.handles.open >= 0"
  # These metric names were established in 6.5.
  when: "version | version_compare('6.5', '>=')"
