# Snapshot builds.
# Published by: https://internal-ci.elastic.co/job/elastic+release-manager+master+unified-snapshot/
beats_url_base: https://snapshots.elastic.co/downloads/beats
version: 8.0.0-SNAPSHOT
