---
- name: Packaging tests Packetbeat
  hosts:
    - debian
    - centos
    - darwin
  become: yes
  tags:
    - packetbeat
  vars:
    - beat_name: packetbeat
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall
    - {role: test-linux-binary, when: ansible_system == "Linux"}

- name: Packaging tests Filebeat
  hosts:
    - debian
    - centos
    - darwin
  become: yes
  tags:
    - filebeat
  vars:
    - beat_name: filebeat
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall
    - {role: test-linux-binary, when: ansible_system == "Linux"}

- name: Packaging tests Metricbeat
  hosts:
    - debian
    - centos
    - darwin
  become: yes
  tags:
    - metricbeat
  vars:
    - beat_name: metricbeat
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall
    - {role: test-linux-binary, when: ansible_system == "Linux"}

- name: Packaging tests Heartbeat
  hosts:
    - debian
    - centos
    - darwin
  become: yes
  tags:
    - heartbeat
  vars:
    - beat_name: heartbeat
    - service_name: heartbeat-elastic
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall
    - {role: test-linux-binary, when: ansible_system == "Linux"}

- name: Packaging tests Auditbeat
  hosts:
    - debian
    - centos
    - darwin
  become: yes
  tags:
    - auditbeat
  vars:
    - beat_name: auditbeat
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall
    - {role: test-linux-binary, when: ansible_system == "Linux"}

# windows
- name: Packaging windows x86 tests for Packetbeat
  hosts:
    - windows
  tags:
    - packetbeat
    - windows
  vars:
    - beat_name: packetbeat
    - win_arch: x86
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86_64 tests for Packetbeat
  hosts:
    - windows
  tags:
    - packetbeat
    - windows
  vars:
    - beat_name: packetbeat
    - win_arch: x86_64
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86 tests for Metricbeat
  hosts:
    - windows
  tags:
    - metricbeat
    - windows
  vars:
    - beat_name: metricbeat
    - win_arch: x86
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86_64 tests for Metricbeat
  hosts:
    - windows
  tags:
    - metricbeat
    - windows
  vars:
    - beat_name: metricbeat
    - win_arch: x86_64
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86 tests for Filebeat
  hosts:
    - windows
  tags:
    - filebeat
    - windows
  vars:
    - beat_name: filebeat
    - win_arch: x86
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86_64 tests for Filebeat
  hosts:
    - windows
  tags:
    - filebeat
    - windows
  vars:
    - beat_name: filebeat
    - win_arch: x86_64
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86 tests for Heartbeat
  hosts:
    - windows
  tags:
    - heartbeat
    - windows
  vars:
    - beat_name: heartbeat
    - win_arch: x86
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86_64 tests for Heartbeat
  hosts:
    - windows
  tags:
    - heartbeat
    - windows
  vars:
    - beat_name: heartbeat
    - win_arch: x86_64
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86 tests for Winlogbeat
  hosts:
    - windows
  tags:
    - winlogbeat
    - windows
  vars:
    - beat_name: winlogbeat
    - win_arch: x86
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86_64 tests for Winlogbeat
  hosts:
    - windows
  tags:
    - winlogbeat
    - windows
  vars:
    - beat_name: winlogbeat
    - win_arch: x86_64
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86 tests for Auditbeat
  hosts:
    - windows
  tags:
    - auditbeat
    - windows
  vars:
    - beat_name: auditbeat
    - win_arch: x86
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall

- name: Packaging windows x86_64 tests for Auditbeat
  hosts:
    - windows
  tags:
    - auditbeat
    - windows
  vars:
    - beat_name: auditbeat
    - win_arch: x86_64
  roles:
    - common
    - test-install
    - test-beat
    - test-uninstall
