#!/usr/bin/env groovy

@Library('apm@current') _

pipeline {
  agent { label 'linux && immutable' }
  environment {
    BASE_DIR = 'src'
    PIPELINE_LOG_LEVEL = 'INFO'
    URL_BASE = "${params.URL_BASE}"
    VERSION = "${params.VERSION}"
    HOME = "${WORKSPACE}"
  }
  options {
    timeout(time: 2, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    quietPeriod(10)
    rateLimitBuilds(throttle: [count: 60, durationName: 'hour', userBoost: true])
  }
  triggers {
    issueCommentTrigger('(?i).*(?:jenkins\\W+)?run\\W+(?:the\\W+)?tests(?:\\W+please)?.*')
  }
  parameters {
    string(name: 'URL_BASE', defaultValue: 'https://storage.googleapis.com/beats-ci-artifacts/snapshots', description: 'The location where the packages should be downloaded from')
    string(name: 'VERSION', defaultValue: '8.0.0-SNAPSHOT', description: 'The package version to test (modify the job configuration to add a new version)')
  }
  stages {
    stage('Checkout') {
      options { skipDefaultCheckout() }
      steps {
        pipelineManager([ cancelPreviousRunningBuilds: [ when: 'PR' ] ])
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}", githubNotifyFirstTimeContributor: true)
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    stage('Test Hosts'){
      matrix {
        agent { label 'linux && immutable' }
        axes {
          axis {
            name 'GROUPS'
            values 'centos', 'debian', 'sles', 'windows'
          }
        }
        stages {
          stage('Test'){
            options { skipDefaultCheckout() }
            steps {
              deleteDir()
              unstash 'source'
              dir("${BASE_DIR}"){
                sh(label: 'make batch',
                  script: """#!/bin/bash
                    echo "url_base: ${URL_BASE}" > run-settings-jenkins.yml
                    echo "version: ${VERSION}" >> run-settings-jenkins.yml
                    RUN_SETTINGS=jenkins make batch""")
              }
            }
            post {
              always {
                dir("${BASE_DIR}"){
                  archiveArtifacts(allowEmptyArchive: true, artifacts: '**/logs/**')
                  sh(label: 'make clean', script: 'make clean')
                }
              }
              cleanup {
                deleteDir()
              }
            }
          }
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult(prComment: true)
    }
  }
}
