#!/usr/bin/env groovy

@Library('apm@current') _

pipeline {
  agent { label 'linux && immutable' }
  environment {
    BASE_DIR = 'src'
    PIPELINE_LOG_LEVEL = 'INFO'
    APM_URL_BASE = "${params.APM_URL_BASE}"
    BEATS_URL_BASE = "${params.BEATS_URL_BASE}"
    VERSION = "${params.VERSION}"
    LANG = "C.UTF-8"
    LC_ALL = "C.UTF-8"
    PYTHONUTF8 = "1"
  }
  options {
    timeout(time: 4, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    quietPeriod(10)
    rateLimitBuilds(throttle: [count: 8, durationName: 'hour', userBoost: true])
  }
  triggers {
    issueCommentTrigger('(?i).*(?:jenkins\\W+)?run\\W+(?:the\\W+)?tests(?:\\W+please)?.*')
  }
  parameters {
    string(name: 'APM_URL_BASE', defaultValue: 'https://storage.googleapis.com/apm-ci-artifacts/jobs/snapshots', description: 'The location where the APM packages should be downloaded from')
    string(name: 'BEATS_URL_BASE', defaultValue: 'https://storage.googleapis.com/beats-ci-artifacts/snapshots', description: 'The location where the Beats packages should be downloaded from')
    string(name: 'VERSION', defaultValue: '8.0.0-SNAPSHOT', description: 'The package version to test (modify the job configuration to add a new version)')
  }
  stages {
    stage('Checkout') {
      options { skipDefaultCheckout() }
      steps {
        pipelineManager([ cancelPreviousRunningBuilds: [ when: 'PR' ] ])
        deleteDir()
        gitCheckout(basedir: "${BASE_DIR}", githubNotifyFirstTimeContributor: true)
        stash allowEmpty: true, name: 'source', useDefaultExcludes: false
      }
    }
    stage('Test Hosts'){
      failFast false
      matrix {
        agent { label 'metal' }
        axes {
          axis {
            name 'GROUPS'
            values 'centos', 'debian', 'sles', 'windows'
          }
        }
        stages {
          stage('Test'){
            options { skipDefaultCheckout() }
            environment {
              VAGRANT_HOME = "${env.HOME}/.vagrant.d"
            }
            steps {
              deleteDir()
              unstash 'source'
              sh(label: 'Debug vagrant context',
                script: """#!/bin/bash
                  env | sort
                  find ${VAGRANT_HOME} -type f -ls || true
                """)
              dir("${BASE_DIR}"){
                sh(label: 'make batch',
                  script: """#!/bin/bash
                    echo "beats_url_base: ${BEATS_URL_BASE}" > run-settings-jenkins.yml
                    echo "apm_url_base: ${APM_URL_BASE}" >> run-settings-jenkins.yml
                    echo "version: ${VERSION}" >> run-settings-jenkins.yml
                    RUN_SETTINGS=jenkins make batch""")
              }
            }
            post {
              always {
                dir("${BASE_DIR}"){
                  junit(allowEmptyResults: true, keepLongStdio: true, testResults: "logs/*.xml")
                  archiveArtifacts(allowEmptyArchive: true, artifacts: 'logs/**')
                  sh(label: 'make clean', script: 'make clean')
                }
              }
              cleanup {
                deleteDir()
              }
            }
          }
        }
      }
    }
  }
  post {
    cleanup {
      notifyBuildResult(prComment: true)
    }
    failure {
      whenFalse(isPR()) {
        slackSend(channel: '#observablt-robots', color: 'danger',
                  message: "Build Failed: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.RUN_DISPLAY_URL}|Open>).",
                  tokenCredentialId: 'jenkins-slack-integration-token')
      }
    }
  }
}
