- name: Compute vars (binary)
  set_fact:
    beat_url: "{{url_base}}/{{beat_name}}/{{beat_name}}-{{version}}-linux-{{bin_arch}}.tar.gz"
    beat_pkg: "{{beat_name}}-{{version}}-linux-{{bin_arch}}.tar.gz"
    beat_cfg: "/tmp/{{beat_name}}-{{version}}-linux-{{bin_arch}}/{{beat_name}}.yml"
    workdir: /tmp
    installdir: /tmp/{{beat_name}}-{{version}}-linux-{{bin_arch}}

- name: Ensure empty output directory
  file: path={{workdir}}/output state=absent

- name: Download package sha1
  get_url: url={{beat_url}}.sha1 dest={{workdir}} validate_certs=no

- name: Download package
  get_url: url={{beat_url}} dest={{workdir}} validate_certs=no

- name: Check file (linux)
  shell: chdir={{workdir}} echo "`cat {{beat_pkg}}.sha1`  {{beat_pkg}}" | sha1sum -c

- name: Create install directory
  file: path={{installdir}} state=directory

- name: Untar
  shell: chdir={{installdir}} tar xzvf {{workdir}}/{{beat_pkg}} --strip 1

- name: Start in bg
  shell: chdir={{installdir}} ./{{beat_name}} -E output.elasticsearch.enabled=false -E output.file.path={{workdir}}/output -E metricbeat.modules.0.period=1s
  async: 45
  poll: 0  # run in bg

- name: Sleep a little
  shell: sleep 1
  always_run: true

- name: Curl something (linux)
  shell: wget google.com
  when: beat_name == "packetbeat"

- name: Wait for the output file to be created, should contain type=http
  wait_for: >
    path={{workdir}}/output/packetbeat timeout=5
    search_regex='"type":"http"'
  when: beat_name == "packetbeat"

- name: Wait for the output file to be created, should contain system load
  wait_for: >
    path={{workdir}}/output/{{beat_name}} timeout=5
    search_regex='"load"'
  when: beat_name == "metricbeat"

- name: Wait for the output file to be created, should contain HTTP pinging
  wait_for: >
    path={{workdir}}/output/heartbeat timeout=5
    search_regex='"scheme":"http"'
  when: beat_name == "heartbeat`"

- name: Check if version number is correct
  shell: chdir={{installdir}} ./{{beat_name}} -version | grep {{ version[0:5] }}
