
- name: Download package sha1
  get_url: url={{beat_url}}.sha1 dest={{workdir}} validate_certs=no
  when: not ansible_os_family == "Windows"

- name: Download package sha1 (windows)
  win_get_url: url={{beat_url}}.sha1 dest={{workdir}}/{{beat_pkg}}.sha1 validate_certs=no
  when: ansible_os_family == "Windows"

- name: Download package
  get_url: url={{beat_url}} dest={{workdir}} validate_certs=no
  when: not ansible_os_family == "Windows"

- name: Download package (windows)
  win_get_url: url={{beat_url}} dest={{workdir}}/{{beat_pkg}} validate_certs=no force=no
  when: ansible_os_family == "Windows"

- name: Check file (linux)
  shell: chdir={{workdir}} echo "`cat {{beat_pkg}}.sha1`  {{beat_pkg}}" | sha1sum -c
  when: ansible_os_family in ["RedHat", "Debian", "Suse"]

- name: Check file (darwin)
  shell: chdir={{workdir}} echo "`cat {{beat_pkg}}.sha1`  {{beat_pkg}}" | shasum -c
  when: ansible_os_family == "Darwin"
