
- name: Download package sha512
  get_url: url={{beat_url}}.sha512 dest={{workdir}} validate_certs=no
  when: not ansible_os_family == "Windows"

- name: Download package sha512 (windows)
  win_get_url: url={{beat_url}}.sha512 dest={{workdir}}/{{beat_pkg}}.sha512 validate_certs=no
  when: ansible_os_family == "Windows"

- name: Download package
  get_url: url={{beat_url}} dest={{workdir}} validate_certs=no
  when: not ansible_os_family == "Windows"

- name: Download package (windows)
  win_get_url: url={{beat_url}} dest={{workdir}}/{{beat_pkg}} validate_certs=no force=no
  when: ansible_os_family == "Windows"

- name: Check file (linux)
  shell: chdir={{workdir}} echo "`cat {{beat_pkg}}.sha512`  {{beat_pkg}}" | sha512sum -c
  when: ansible_os_family in ["RedHat", "Debian", "Suse"]

- name: Check file (darwin)
  shell: chdir={{workdir}} echo "`cat {{beat_pkg}}.sha512`  {{beat_pkg}}" | shasum -a 512 -c
  when: ansible_os_family == "Darwin"
