- name: Download beat checksum (linux/darwin)
  get_url:
    url: "{{beat_url_sha}}"
    dest: "{{workdir}}/beat_sha512.txt"
  when: ansible_os_family != "Windows"

- name: Extract beat checksum (linux/darwin)
  vars:
    beat_url_sha: "{{ beat_url }}.sha512"
  set_fact: beat_sha512="{{ lookup('url', beat_url_sha, split_lines=False) | trim }}"
  when: ansible_os_family != "Windows"

- name: Print checksum info
  ansible.builtin.debug:
    var: beat_sha512
    verbosity: 2

- name: Download package with checksum (linux/darwin)
  get_url:
    url: "{{beat_url}}"
    dest: "{{workdir}}"
    validate_certs: no
    timeout: 60
    checksum: "sha512:{{ beat_sha512 }}"
  when: ansible_os_family != "Windows"

- name: Download package with checksum (windows)
  win_get_url:
    url: "{{beat_url}}"
    dest: "{{workdir}}"
    validate_certs: no
    timeout: 60
    checksum_url: "{{beat_url}}.sha512"
    checksum_algorithm: sha512
  when: ansible_os_family == "Windows"
