- name: Download package with checksum (linux/darwin)
  vars:
    - beat_sha512: "{{ lookup('url', beat_url + '.sha512', split_lines=False) | trim }}"
  get_url:
    url: "{{beat_url}}"
    dest: "{{workdir}}"
    validate_certs: no
    timeout: 60
    checksum: "sha512:{{ beat_sha512.split()[0] }}"
  when: ansible_os_family != "Windows"

- name: Download package with checksum (windows)
  win_get_url:
    url: "{{beat_url}}"
    dest: "{{workdir}}"
    validate_certs: no
    timeout: 60
    checksum_url: "{{beat_url}}.sha512"
    checksum_algorithm: sha512
  when: ansible_os_family == "Windows"
