
- name: Download package with checksum (linux/darwin)
  get_url:
    url: "{{beat_url}}"
    dest: "{{workdir}}"
    validate_certs: no
    timeout: 60
    checksum: "sha512:{{beat_url}}.sha512"
  when: ansible_os_family != "Windows"

- name: Download package with checksum (windows)
  get_url:
    url: "{{beat_url}}"
    dest: "{{workdir}}"
    validate_certs: no
    timeout: 60
    checksum: "sha512:{{beat_url}}.sha512"
  when: ansible_os_family == "Windows"
