- name: Compute vars (debian)
  set_fact:
    beat_url: "{{ url_base }}/{{url_dir}}{{beat_name}}{{beat_pkg_suffix}}-{{version}}-{{deb_arch}}.deb"
    beat_pkg: "{{beat_name}}{{beat_pkg_suffix}}-{{version}}-{{deb_arch}}.deb"
    beat_cfg: "/etc/{{beat_name}}/{{beat_name}}.yml"
    workdir: /root
  when: ansible_os_family == "Debian"

- name: Compute vars (redhat)
  set_fact:
    beat_url: "{{url_base}}/{{url_dir}}{{beat_name}}{{beat_pkg_suffix}}-{{version}}-{{rpm_arch}}.rpm"
    beat_pkg: "{{beat_name}}{{beat_pkg_suffix}}-{{version}}-{{rpm_arch}}.rpm"
    beat_cfg: "/etc/{{beat_name}}/{{beat_name}}.yml"
    workdir: /root
  when: ansible_os_family in ["RedHat", "Suse"]

- name: Compute vars (darwin)
  set_fact:
    beat_url: "{{url_base}}/{{url_dir}}{{beat_name}}{{beat_pkg_suffix}}-{{version}}-darwin-x86_64.tar.gz"
    beat_pkg: "{{beat_name}}{{beat_pkg_suffix}}-{{version}}-darwin-x86_64.tar.gz"
    beat_cfg: "/tmp/{{beat_name}}-{{version}}-darwin-x86_64/{{beat_name}}.yml"
    workdir: /tmp
    installdir: /tmp/{{beat_name}}-{{version}}-darwin-x86_64
  when: ansible_os_family == "Darwin"

- name: Compute vars (windows)
  set_fact:
    beat_cfg: '{{ ansible_user_dir }}\{{beat_name}}-{{version}}-windows-{{win_arch}}\{{beat_name}}.yml'
    beat_url: '{{url_base}}/{{url_dir}}{{beat_name}}{{ beat_pkg_suffix }}-{{version}}-windows-{{win_arch}}.zip'
    beat_pkg: '{{beat_name}}{{ beat_pkg_suffix }}-{{version}}-windows-{{win_arch}}.zip'
    workdir: '{{ ansible_user_dir }}'
    installdir: '{{ ansible_user_dir }}\{{beat_name}}-{{version}}-windows-{{win_arch}}'
  when: ansible_os_family == "Windows"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

# CentOS 8 reached end of life, see https://forketyfork.medium.com/centos-8-no-urls-in-mirrorlist-error-3f87c3466faa
- name: 'Comment out mirrorlist in yum.repos.d'
  shell: sudo sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
  become: yes
  when: ansible_os_family == "RedHat"

- name: 'Use vault.centos.org in yum.repos.d'
  shell: sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
  become: yes
  when: ansible_os_family == "RedHat"

- name: Download package and checksum
  include_tasks: download.yml
