---

# The default registry file path changed with 7.0 and 7.9
registry_file: '{{ "registry/filebeat/log.json" if version is version_compare("7.9", ">=") elif version is version_compare("7.0", ">=") "registry/filebeat/data.json" else "registry" }}'
filebeat_logs_dir: '{{ ansible_user_dir }}/filebeat_logs'
