- name: Ensure empty output directory
  win_file: path={{workdir}}\\output state=absent

- name: Replace configuration file (windows)
  win_copy: src={{beat_name}}.yml dest={{installdir}}

- name: Install service
  script: run_script.ps1 -script {{installdir}}\\install-service-{{beat_name}}.ps1

- name: Delete logs directory
  win_file: path=c:\logs state=absent

- name: Start heartbeat
  win_service: name={{beat_name}} state=started

- name: Sleep a little
  script: sleep.ps1 -duration 10

- name: Stat output file
  win_stat: path={{workdir}}\output\{{beat_name}}
  register: output_stat

- debug: var=output_stat

- name: Check output file
  assert:
    that:
      - "output_stat.stat.exists"
      - "output_stat.stat.size > 250"

- name: Stop heartbeat
  win_service: name={{beat_name}} state=stopped

- name: Uninstall service
  script: run_script.ps1 -script {{installdir}}\\uninstall-service-{{beat_name}}.ps1
